server:
  port: 8091

spring:
  application:
    name: bank-account-details
  datasource:
    url: jdbc:mysql://localhost:3306/favourite?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true     

